### PR TITLE
Update Adafruit_Arcada_Alerts.cpp

### PR DESCRIPTION
**Pull request by Tijgerd**
Added documentation to:
uint8_t Adafruit_Arcada::menu(const char **menu_strings, uint8_t menu_num, boxColor, uint16_t textColor);

### CODE REVIEW

**Comment by Tijgerd** [comment]
Can this be reviewed by @ladyada ? ( or any another member from Adafruit :) )

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
aww thanks! was going to do this but fell asleep :)

**Comment by Tijgerd** [comment]
I love this project btw, I think it is more appealing to the younger audience to actually see their code come to life!
A while ago I had a similar idea but didn't have the resources (time) to build it all from the start.
For now, I will keep an eye on this project and contribute in any way I can.
Anything that needs to, or can be right away?

I have a lot of experience with embedded C++ programming (mostly ARM based) so just "throw a bone" in the issue section and I will see what I can do :)

**Comment by ladyada** [comment]
thanks - we'll be doing most of the coding for a bit but feel free to add in functions as PRs if you have any ideas!

**Pull request merged**
